services:
  syncthing:
    image: syncthing/syncthing:2.0.10
    container_name: syncthing
    hostname: ${HOSTNAME}
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - data:/var/syncthing
    ports:
      - ${PORT}:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    restart: unless-stopped
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3

volumes:
  data:
    name: ${COMPOSE_PROJECT_NAME}_${VOLUME_NAME}

